version: 2
jobs:
  build:
    docker:
      - image: 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY


    working_directory: ~/repo

    environment:
     # Customize the JVM maximum heap limit
        MAVEN_OPTS: -Xmx3200m

    steps:
        - checkout
     # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
         # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        - run: mvn integration-test

        - run: mvn install
  deploy:
    docker:
      - image: 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
       - run: mvn integration-test

       - run: mvn install

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/
